### ISSUE TITLE
Add rules for avalon

### ISSUE THREAD

**Issue by kaw2k** [kaw2k/lunch-games#3]
In the Avalon lobby, let's make another tab at the bottom with rules. This will be similar to how Skull and Secret Hitler have their rules. The rules don't need to be complete, but a high level would be good (two teams, voting on missions, etc)

**Comment by michalhus** [comment]
https://github.com/kaw2k/lunch-games/pull/6

**Comment by michalhus** [comment]
Issue resolved with a merge of PR #6 
Note: Might need to add some more rules in the future (i.e. 4th mission needs 2 fails, etc.)
